name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.TOKEN_20240523_USERNAME }}
        password: ${{ secrets.TOKEN_20240521 }}

    - name: Build and Push
      uses: docker/build-push-action@v2
      with:
        context:
        push: true
        tags: ritz2016/ntt-east-postgis:16.2
